# config.yaml
paths:
  input_list: "../../shared-data/input.csv"
  output_folder: "../../shared-data/pdfs"
  template_path: "invoice_template/invoice.html"
  whatsapp_output_file: "../../shared-data/output.json"
  invoice_configs: "../../shared-data/invoice_configs.yaml"

whatsapp:
  template_good: "*Patronato San Roberto de Sula*\n\nEstimado(a) {name}, adjuntamos su factura de {month} {year}.\n\n‚úÖ *Usted est√° AL D√çA*\n\n¬°Gracias por su apoyo a la comunidad!\n\nPuede verificar su estado de cuenta aqu√≠: www.sanrobertodesula.org/estado/?lote={lot}"
  template_bad: "*Patronato San Roberto de Sula*\n\nEstimado(a) {name}, adjuntamos su factura de {month} {year}.\n\nüí≥ *Saldo total: L. {pending} (incluye cuota de {month})*\n\nLa cuota vigente puede cancelarse hasta fin de mes. Puede verificar su estado de cuenta aqu√≠: www.sanrobertodesula.org/estado/?lote={lot}\n\nCualquier consulta sobre su estado de cuenta, estamos para servirle."
