# config.yaml
paths:
  input_list: "../../shared-data/input.csv"
  output_folder: "../../shared-data/pdfs"
  template_path: "invoice_template/invoice.html"
  whatsapp_output_file: "../../shared-data/output.json"
  invoice_configs: "../../shared-data/invoice_configs.yaml"

whatsapp:
  template_good: "*Patronato San Roberto de Sula*\n\nEstimado(a) {name}, adjuntamos su factura de {month} {year}.\n\nâœ… *Usted estÃ¡ AL DÃA*\n\nÂ¡Gracias por su apoyo a la comunidad!"
  template_bad: "*Patronato San Roberto de Sula*\n\nEstimado(a) {name}, adjuntamos su factura de {month} {year}.\n\nğŸ’³ *Saldo total: L. {pending} (incluye cuota de {month})*\n\nÂ¡Gracias por su compromiso con la colonia! Le recordamos que la cuota actual puede ser cancelada hasta fin de mes. Si tiene meses anteriores sin cancelar, le animamos a regularizar su cuenta para que juntos sigamos realizando mejoras.\n\nCualquier consulta sobre su estado de cuenta, estamos para servirle."
